name: differ
on:
  push:

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: diff
      run: |
        diff <(cat name1.txt) <cat name2.txt)
