name: differ
on:
  push:

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: diff
      run: |
        diff <(cat names1.txt) <(cat names2.txt) | cat > temp.diff
        cat temp.diff | grep bob | cat
